#' @importFrom SeuratObject CreateSeuratObject
#' @keywords internal
"_PACKAGE"

#' Load the combined 10x Genomics PBMC single-cell reference dataset
#'
#' Loads a processed single-cell RNA-seq reference dataset generated by combining
#' publicly available peripheral blood mononuclear cell (PBMC) datasets from
#' healthy donors provided by 10x Genomics. The reference combines the 6k PBMC,
#' 8k PBMC, and 10k PBMC datasets and was processed, annotated, filtered, and
#' formatted for use in QUASAR deconvolution workflows.
#'
#' The returned object is a processed Seurat object containing 22,629 features
#' across 21,978 cells. The active assay is `RNA`, with 22,629 features and
#' 0 variable features. The assay contains only one layer: `counts`.
#'
#' Cell type annotations are stored in the object metadata column `celltype`.
#' The dataset contains the following annotated cell types:
#'
#' \describe{
#'   \item{Bcells}{3,352 cells}
#'   \item{CD4Tcells}{8,181 cells}
#'   \item{CD8Tcells}{3,329 cells}
#'   \item{Monocytes}{5,428 cells}
#'   \item{NK}{1,586 cells}
#'   \item{Unknown}{102 cells}
#' }
#'
#' Dataset-of-origin information is stored in the metadata column `donor_id`.
#' The combined reference contains:
#'
#' \describe{
#'   \item{pbmc10k}{9,141 cells}
#'   \item{pbmc6k}{4,658 cells}
#'   \item{pbmc8k}{8,179 cells}
#' }
#'
#' The original 10x Genomics datasets are licensed under the Creative Commons
#' Attribution 4.0 International License (CC BY 4.0). The data included here
#' were processed, annotated, filtered, and reformatted by Sergej Ruff. No
#' endorsement by 10x Genomics is implied.
#'
#' @return A processed Seurat object with 22,629 features and 21,978 cells.
#' The object contains one assay, `RNA`, with the layer `counts`. Cell type
#' labels are stored in `celltype`, and dataset-origin labels are stored in
#' `donor_id`.
#'
#' @source
#' 10x Genomics:
#' \itemize{
#'   \item 6k PBMCs from a Healthy Donor, Universal 3' dataset analyzed using Cell Ranger 1.1.0.
#'   \item 8k PBMCs from a Healthy Donor, Universal 3' dataset analyzed using Cell Ranger 2.1.0.
#'   \item 10k PBMCs from a Healthy Donor (v3 chemistry), Universal 3' dataset analyzed using Cell Ranger 3.0.0.
#' }
#'
#' Original datasets: \url{https://www.10xgenomics.com/resources/datasets}
#'
#' License: Creative Commons Attribution 4.0 International,
#' \url{https://creativecommons.org/licenses/by/4.0/}
#'
#' @examples
#' 
#' pbmc_sc_ref <- load_pbmc_sc_ref()
#'
#' pbmc_sc_ref
#'
#' table(pbmc_sc_ref$celltype)
#' table(pbmc_sc_ref$donor_id)
#'
#' @export
load_pbmc_sc_ref <- function() {
  path <- system.file(
    "extdata",
    "pbmc_sc_ref.rds",
    package = "QuasarDeconData",
    mustWork = TRUE
  )

  readRDS(path)
}



#' Processed GSE107011 PBMC bulk deconvolution dataset
#'
#' A processed peripheral blood mononuclear cell (PBMC) bulk RNA-seq
#' deconvolution dataset derived from GEO accession GSE107011. The original
#' study profiled immune cell types and PBMC samples and used the data for
#' transcriptomic characterization and deconvolution analyses.
#'
#' The object is provided as a named list with bulk expression profiles,
#' experimentally derived ground-truth cell type proportions, and gene
#' identifiers. It was processed and formatted for use in QUASAR deconvolution
#' workflows.
#'
#' The object contains the following elements:
#'
#' \describe{
#'   \item{ground_truth_proportions}{
#'     A numeric matrix or data frame with 12 samples and 6 cell type columns.
#'     The columns are `Bcells`, `CD4Tcells`, `CD8Tcells`, `Monocytes`, `NK`,
#'     and `Unknown`.
#'   }
#'   \item{bulk_expression_profiles}{
#'     A numeric matrix or data frame with 36,128 features and 12 bulk PBMC
#'     samples.
#'   }
#'   \item{ensembl_ids}{
#'     Gene identifiers corresponding to the rows of `bulk_expression_profiles`.
#'   }
#' }
#'
#' Ground-truth cell type proportions are available for the following cell
#' types:
#'
#' \describe{
#'   \item{Bcells}{B cells}
#'   \item{CD4Tcells}{CD4 T cells}
#'   \item{CD8Tcells}{CD8 T cells}
#'   \item{Monocytes}{Monocytes}
#'   \item{NK}{Natural killer cells}
#'   \item{Unknown}{Unassigned or remaining cell type fraction}
#' }
#'
#' The data included here were processed and reformatted by Sergej Ruff for use
#' with QUASAR deconvolution workflows. No endorsement by the original data
#' providers is implied.
#'
#' @format A named list with three elements:
#' \describe{
#'   \item{ground_truth_proportions}{
#'     A 12 x 6 matrix or data frame containing ground-truth PBMC cell type
#'     proportions.
#'   }
#'   \item{bulk_expression_profiles}{
#'     A 36,128 x 12 matrix or data frame containing bulk expression profiles.
#'   }
#'   \item{ensembl_ids}{
#'     A vector of Ensembl gene identifiers corresponding to the expression
#'     profile rows.
#'   }
#' }
#'
#' @source
#' Gene Expression Omnibus accession GSE107011:
#' \url{https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE107011}
#'
#' Monaco G, Lee B, Xu W, Mustafah S, Hwang YY, Carré C, Burdin N,
#' Visan L, Ceccarelli M, Poidinger M, Zippelius A, Pedro de Magalhães J,
#' Larbi A. RNA-Seq Signatures Normalized by mRNA Abundance Allow Absolute
#' Deconvolution of Human Immune Cell Types. Cell Reports.
#'
#' @usage data(GSE107011)
#'
#' @keywords datasets
#'
#' @examples
#' data(GSE107011)
#'
#' names(GSE107011)
#' dim(GSE107011$bulk_expression_profiles)
#' dim(GSE107011$ground_truth_proportions)
#' colnames(GSE107011$ground_truth_proportions)
"GSE107011"


#' Processed GSE107572 PBMC bulk deconvolution dataset
#'
#' A processed peripheral blood mononuclear cell (PBMC) bulk RNA-seq
#' deconvolution dataset derived from GEO accession GSE107572. The original
#' GEO series is associated with the quanTIseq study and contains
#' blood-derived immune-cell mixtures from 9 healthy donors. The experiment was
#' performed in Homo sapiens using high-throughput RNA sequencing.
#'
#' The object is provided as a named list with bulk expression profiles and
#' experimentally derived ground-truth cell type proportions. It was processed
#' and formatted for use in QUASAR deconvolution workflows.
#'
#' The object contains the following elements:
#'
#' \describe{
#'   \item{ground_truth_proportions}{
#'     A numeric matrix or data frame with 9 samples and 6 cell type columns.
#'     The columns are `CD4Tcells`, `CD8Tcells`, `NK`, `Bcells`, `Monocytes`,
#'     and `Unknown`.
#'   }
#'   \item{bulk_expression_profiles}{
#'     A numeric matrix or data frame with 19,423 features and 9 bulk PBMC
#'     samples.
#'   }
#' }
#'
#' Ground-truth cell type proportions are available for the following cell
#' types:
#'
#' \describe{
#'   \item{CD4Tcells}{CD4 T cells}
#'   \item{CD8Tcells}{CD8 T cells}
#'   \item{NK}{Natural killer cells}
#'   \item{Bcells}{B cells}
#'   \item{Monocytes}{Monocytes}
#'   \item{Unknown}{Unassigned or remaining cell type fraction}
#' }
#'
#' The data included here were processed and reformatted by Sergej Ruff for use
#' with QUASAR deconvolution workflows. No endorsement by the original data
#' providers is implied.
#'
#' @format A named list with two elements:
#' \describe{
#'   \item{ground_truth_proportions}{
#'     A 9 x 6 matrix or data frame containing ground-truth PBMC cell type
#'     proportions.
#'   }
#'   \item{bulk_expression_profiles}{
#'     A 19,423 x 9 matrix or data frame containing bulk expression profiles.
#'   }
#' }
#'
#' @source
#' Gene Expression Omnibus accession GSE107572:
#' \url{https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE107572}
#'
#' Finotello F, Mayer C, Plattner C, Laschober G, Rieder D, Hackl H,
#' Krogsdam A, Posch W, Wilflingseder D, Sopper S, Jsselsteijn M, Johnsons D,
#' Xu Y, Wang Y, Sanders ME, Estrada MV, Ericsson-Gonzalez P, Balko J,
#' de Miranda NF, Trajanoski Z. Molecular and pharmacological modulators of
#' the tumor immune contexture revealed by deconvolution of RNA-seq data.
#'
#' @usage data(GSE107572)
#'
#' @keywords datasets
#'
#' @examples
#' data(GSE107572)
#'
#' names(GSE107572)
#' dim(GSE107572$bulk_expression_profiles)
#' dim(GSE107572$ground_truth_proportions)
#' colnames(GSE107572$ground_truth_proportions)
"GSE107572"


#' Processed GSE120502 PBMC bulk deconvolution dataset
#'
#' A processed peripheral blood mononuclear cell (PBMC) bulk RNA-seq
#' deconvolution dataset derived from GEO accession GSE120502. The original
#' GEO series contains human PBMC RNA-seq samples and has been used as a
#' benchmark dataset for bulk RNA-seq deconvolution with ground-truth cell type
#' proportions. 
#'
#' The object is provided as a named list with bulk expression profiles,
#' ground-truth cell type proportions, and gene identifiers. It was processed
#' and formatted for use in QUASAR deconvolution workflows.
#'
#' The object contains the following elements:
#'
#' \describe{
#'   \item{ground_truth_proportions}{
#'     A numeric matrix or data frame with 249 samples and 6 cell type columns.
#'     The columns are `Monocytes`, `Bcells`, `CD4Tcells`, `NK`, `CD8Tcells`,
#'     and `Unknown`.
#'   }
#'   \item{bulk_expression_profiles}{
#'     A numeric matrix or data frame with 39,376 features and 249 bulk PBMC
#'     samples.
#'   }
#'   \item{gene_ids}{
#'     Gene identifiers corresponding to the rows of `bulk_expression_profiles`.
#'   }
#' }
#'
#' Ground-truth cell type proportions are available for the following cell
#' types:
#'
#' \describe{
#'   \item{Monocytes}{Monocytes}
#'   \item{Bcells}{B cells}
#'   \item{CD4Tcells}{CD4 T cells}
#'   \item{NK}{Natural killer cells}
#'   \item{CD8Tcells}{CD8 T cells}
#'   \item{Unknown}{Unassigned or remaining cell type fraction}
#' }
#'
#' The data included here were processed and reformatted by Sergej Ruff for use
#' with QUASAR deconvolution workflows. No endorsement by the original data
#' providers is implied.
#'
#' @format A named list with three elements:
#' \describe{
#'   \item{ground_truth_proportions}{
#'     A 249 x 6 matrix or data frame containing ground-truth PBMC cell type
#'     proportions.
#'   }
#'   \item{bulk_expression_profiles}{
#'     A 39,376 x 249 matrix or data frame containing bulk expression profiles.
#'   }
#'   \item{gene_ids}{
#'     A vector of gene identifiers corresponding to the expression profile rows.
#'   }
#' }
#'
#' @source
#' Gene Expression Omnibus accession GSE120502:
#' \url{https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE120502}
#'
#'
#' @usage data(GSE120502)
#'
#' @keywords datasets
#'
#' @examples
#' data(GSE120502)
#'
#' names(GSE120502)
#' dim(GSE120502$bulk_expression_profiles)
#' dim(GSE120502$ground_truth_proportions)
#' colnames(GSE120502$ground_truth_proportions)
"GSE120502"


#' Processed GSE65133 PBMC bulk deconvolution dataset
#'
#' A processed peripheral blood mononuclear cell (PBMC) bulk expression
#' deconvolution dataset derived from GEO accession GSE65133. The original
#' GEO series is associated with the CIBERSORT study, "Robust enumeration of
#' cell subsets from tissue expression profiles", and contains expression
#' profiles from 20 PBMC samples from adults of varying ages receiving
#' influenza immunization. The samples were profiled using the Illumina
#' HumanHT-12 V4.0 expression beadchip platform and were accompanied by flow
#' cytometry measurements of leukocyte subset proportions.
#'
#' The object is provided as a named list with bulk expression profiles,
#' ground-truth cell type proportions, and probe identifiers. It was processed
#' and formatted for use in QUASAR deconvolution workflows.
#'
#' The object contains the following elements:
#'
#' \describe{
#'   \item{ground_truth_proportions}{
#'     A numeric matrix or data frame with 20 samples and 6 cell type columns.
#'     The columns are `Monocytes`, `Unknown`, `CD4Tcells`, `Bcells`, `NK`,
#'     and `CD8Tcells`.
#'   }
#'   \item{bulk_expression_profiles}{
#'     A numeric matrix or data frame with 35,688 features and 20 bulk PBMC
#'     samples.
#'   }
#'   \item{probe_ids}{
#'     Probe identifiers corresponding to the rows of
#'     `bulk_expression_profiles`.
#'   }
#' }
#'
#' Ground-truth cell type proportions are available for the following cell
#' types:
#'
#' \describe{
#'   \item{Monocytes}{Monocytes}
#'   \item{Unknown}{Unassigned or remaining cell type fraction}
#'   \item{CD4Tcells}{CD4 T cells}
#'   \item{Bcells}{B cells}
#'   \item{NK}{Natural killer cells}
#'   \item{CD8Tcells}{CD8 T cells}
#' }
#'
#' The data included here were processed and reformatted by Sergej Ruff for use
#' with QUASAR deconvolution workflows. No endorsement by the original data
#' providers is implied.
#'
#' @format A named list with three elements:
#' \describe{
#'   \item{ground_truth_proportions}{
#'     A 20 x 6 matrix or data frame containing ground-truth PBMC cell type
#'     proportions.
#'   }
#'   \item{bulk_expression_profiles}{
#'     A 35,688 x 20 matrix or data frame containing bulk expression profiles.
#'   }
#'   \item{probe_ids}{
#'     A vector of probe identifiers corresponding to the expression profile
#'     rows.
#'   }
#' }
#'
#' @source
#' Gene Expression Omnibus accession GSE65133:
#' \url{https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE65133}
#'
#' Newman AM, Liu CL, Green MR, Gentles AJ, Feng W, Xu Y, Hoang CD,
#' Diehn M, Alizadeh AA, Maecker H, Davis MM. Robust enumeration of cell
#' subsets from tissue expression profiles. Nature Methods. 2015;12(5):453-457.
#' PMID: 25822800.
#'
#' @usage data(GSE65133)
#'
#' @keywords datasets
#'
#' @examples
#' data(GSE65133)
#'
#' names(GSE65133)
#' dim(GSE65133$bulk_expression_profiles)
#' dim(GSE65133$ground_truth_proportions)
#' colnames(GSE65133$ground_truth_proportions)
"GSE65133"


#' Load the COVID-19 PBMC immune reference (train or test split)
#'
#' Loads one half of a donor-balanced 50/50 split of a COVID-19 peripheral-blood
#' immune dataset, shipped in \code{inst/extdata}. The two halves balance mild and
#' severe COVID-19 donors so neither split is enriched for disease severity.
#'
#' @param which Which split to load: \code{"train"} (default) or \code{"test"}.
#' @param project Project name for the resulting object. Defaults to
#'   \code{paste0(which, "_cov")}.
#'
#' @return A \code{\link[SeuratObject]{Seurat}} object with a single \code{counts}
#'   layer, cell-type identities set, and \code{meta.data} columns
#'   \code{cell_type} and \code{donor_id}.
#'
#' @details
#' To keep the packaged \code{.rds} files under 100 MB, the sparse count matrix is
#' stored in CSC form with its values as 32-bit floats. On load the values are
#' read back into double precision, accurate to ~7 significant digits relative to
#' the source; no genes or cells are dropped. \code{donor_id} is retained for
#' deconvolution methods that require per-subject information, e.g. MuSiC.
#'
#' Source: CELLxGENE collection
#' \url{https://cellxgene.cziscience.com/collections/b9fc3d70-5a72-4479-a046-c2cc1ab19efc}.
#'
#' @examples
#' \dontrun{
#' train <- load_cov_imm()          # training split (default)
#' test  <- load_cov_imm("test")    # test split
#' }
#'
#' @importFrom methods new
#' @importClassesFrom Matrix dgCMatrix
#' @importFrom SeuratObject CreateSeuratObject Idents `Idents<-`
#' @export
load_cov_imm <- function(which = c("train", "test"), project = NULL) {
  which <- match.arg(which)
  if (is.null(project)) project <- paste0(which, "_cov")

  file <- system.file("extdata", paste0(which, "_cov.rds"), package = "QUASAR")
  if (!nzchar(file) || !file.exists(file))
    stop("Packaged file not found: ", which, "_cov.rds", call. = FALSE)

  d <- readRDS(file)
  x <- readBin(d$x, "double", n = d$n, size = 4L)
  m <- new("dgCMatrix", i = d$i, p = d$p, x = x, Dim = d$Dim, Dimnames = d$dn)

  obj <- CreateSeuratObject(counts = m, meta.data = d$meta,
                            assay = "RNA", project = project)
  Idents(obj) <- obj$cell_type
  obj
}